/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import java.sql.*;
import Classes.Turma;
import Classes.Secretaria;
import Classes.Director;
import Classes.Professor;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samuel
 */
public class Diretoria extends javax.swing.JFrame {

     //Criando novo formulário Diretoria
     
    public Diretoria() {
        initComponents();
        Connect();
     
        fetch();
    }
    Connection con;
    PreparedStatement pst;
    PreparedStatement sql;
    PreparedStatement sqlUsuario, sqlTelefone;
    ResultSet rs;

    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/solar", "root","1234@");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE,null,ex);
        } catch (SQLException ex) {
            Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void fetch(){
        int i;
        try {
            pst = con.prepareStatement("SELECT*FROM funcionario JOIN usuario on funcionario.idFuncionario=usuario.fk_idFuncionario join cargo ON funcionario.fk_idCargo=cargo.idCargo");
            rs = pst.executeQuery();
            ResultSetMetaData rsm = rs.getMetaData();
            i = rsm.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jTableVisualizarUsuarios.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int j=1; j<=i; j++){
                     v2.add(rs.getString("idFuncionario"));
                    v2.add(rs.getString("nomeFuncionario"));
                    v2.add(rs.getString("genero"));
                    v2.add(rs.getString("nomeUsuario"));
                    v2.add(rs.getString("nomeCargo"));
                }
                df.addRow(v2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genero = new javax.swing.ButtonGroup();
        jDialogEditarUsuario = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnPesquisarUsuario = new javax.swing.JButton();
        editarGenero = new javax.swing.ButtonGroup();
        bgDiretoria = new javax.swing.JPanel();
        bgSidePanel = new javax.swing.JPanel();
        btnNovousuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        btnVisualizarUuarios = new javax.swing.JButton();
        btnCriarTurmas = new javax.swing.JButton();
        btnMainDiretoria = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jTabbedPaneDiretoria = new javax.swing.JTabbedPane();
        jPanelPrincipalDiretoria = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanelCriarTurma = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        txtNomeTurma = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtNumSala = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnCriarTurma = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtIdProfessor = new javax.swing.JTextField();
        jPanelNovoUsuario = new javax.swing.JPanel();
        rdbFemenino = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        area = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtConfSenha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        txtNomeCompleto = new javax.swing.JTextField();
        txtNomeUsuario = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rdbMasculino = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        btnCadastrarUsuario = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanelEditarUsuarios = new javax.swing.JPanel();
        jPanelEditarUsuario = new javax.swing.JPanel();
        rdbEditarFemenino = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        cbxEditarArea = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        editarConfSenha = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        editarSenha = new javax.swing.JTextField();
        txtEditarNomeCompleto = new javax.swing.JTextField();
        txtEditarNomeUsuario = new javax.swing.JTextField();
        txtEditarTelefone = new javax.swing.JTextField();
        btnEditarSalvar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        rdbEditarMasculino = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jPanelVisualizarUsuarios = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVisualizarUsuarios = new javax.swing.JTable();

        jDialogEditarUsuario.setTitle("Busca Usuario");
        jDialogEditarUsuario.setMinimumSize(new java.awt.Dimension(390, 320));

        jLabel33.setText("Digite o ID do usuario");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnPesquisarUsuario.setText("Pesquisar");
        btnPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogEditarUsuarioLayout = new javax.swing.GroupLayout(jDialogEditarUsuario.getContentPane());
        jDialogEditarUsuario.getContentPane().setLayout(jDialogEditarUsuarioLayout);
        jDialogEditarUsuarioLayout.setHorizontalGroup(
            jDialogEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditarUsuarioLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jDialogEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisarUsuario)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jDialogEditarUsuarioLayout.setVerticalGroup(
            jDialogEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditarUsuarioLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisarUsuario)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diretoria");

        bgDiretoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgSidePanel.setBackground(new java.awt.Color(255, 153, 0));
        bgSidePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bgSidePanel.setName(""); // NOI18N
        bgSidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNovousuario.setBackground(new java.awt.Color(255, 153, 0));
        btnNovousuario.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnNovousuario.setForeground(new java.awt.Color(255, 255, 255));
        btnNovousuario.setText("Novo Usuário");
        btnNovousuario.setBorder(null);
        btnNovousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovousuarioActionPerformed(evt);
            }
        });
        bgSidePanel.add(btnNovousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 320, 60));

        btnEditarUsuario.setBackground(new java.awt.Color(255, 153, 0));
        btnEditarUsuario.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarUsuario.setText("Editar Usuário");
        btnEditarUsuario.setBorder(null);
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });
        bgSidePanel.add(btnEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 320, 60));

        btnVisualizarUuarios.setBackground(new java.awt.Color(255, 153, 0));
        btnVisualizarUuarios.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnVisualizarUuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarUuarios.setText("Visualizar Usuários");
        btnVisualizarUuarios.setBorder(null);
        btnVisualizarUuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarUuariosActionPerformed(evt);
            }
        });
        bgSidePanel.add(btnVisualizarUuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 320, 60));

        btnCriarTurmas.setBackground(new java.awt.Color(255, 153, 0));
        btnCriarTurmas.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnCriarTurmas.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarTurmas.setText("Criar Turmas");
        btnCriarTurmas.setBorder(null);
        btnCriarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarTurmasActionPerformed(evt);
            }
        });
        bgSidePanel.add(btnCriarTurmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 320, 60));

        btnMainDiretoria.setBackground(new java.awt.Color(255, 153, 0));
        btnMainDiretoria.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnMainDiretoria.setForeground(new java.awt.Color(255, 255, 255));
        btnMainDiretoria.setText("Home");
        btnMainDiretoria.setBorder(null);
        btnMainDiretoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainDiretoriaActionPerformed(evt);
            }
        });
        bgSidePanel.add(btnMainDiretoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 320, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo solar.png"))); // NOI18N
        bgSidePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnSair.setText("sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        bgSidePanel.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        bgDiretoria.add(bgSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 610));

        jTabbedPaneDiretoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTabbedPaneDiretoriaFocusLost(evt);
            }
        });

        jPanelPrincipalDiretoria.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipalDiretoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Bem-vindo à Diretoria");
        jPanelPrincipalDiretoria.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 320, 61));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/executivo.png"))); // NOI18N
        jPanelPrincipalDiretoria.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 82, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("a gestão escolar eficiente.");
        jPanelPrincipalDiretoria.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, 60));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("O centro de comando para criar e gerenciar usuários,");
        jPanelPrincipalDiretoria.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("formar turmas e visualizar perfis, facilitando");
        jPanelPrincipalDiretoria.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, 60));

        jTabbedPaneDiretoria.addTab("", jPanelPrincipalDiretoria);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel27.setText("CRIAR TURMA");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        txtNomeTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeTurmaActionPerformed(evt);
            }
        });
        jPanel3.add(txtNomeTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 390, -1));

        jLabel29.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel29.setText("Nome da turma:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 120, -1));

        txtNumSala.setText(" ");
        jPanel3.add(txtNumSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 390, -1));

        jLabel30.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel30.setText("ID Professor da turma:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jLabel32.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel32.setText("Número da sala:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 140, 20));

        jLabel34.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel34.setText("Informações da Turma ");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btnCriarTurma.setBackground(new java.awt.Color(255, 153, 0));
        btnCriarTurma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCriarTurma.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarTurma.setText("Confirmar");
        btnCriarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarTurmaActionPerformed(evt);
            }
        });
        jPanel3.add(btnCriarTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, 30));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 80, 30));
        jPanel3.add(txtIdProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 130, -1));

        javax.swing.GroupLayout jPanelCriarTurmaLayout = new javax.swing.GroupLayout(jPanelCriarTurma);
        jPanelCriarTurma.setLayout(jPanelCriarTurmaLayout);
        jPanelCriarTurmaLayout.setHorizontalGroup(
            jPanelCriarTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
            .addGroup(jPanelCriarTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCriarTurmaLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelCriarTurmaLayout.setVerticalGroup(
            jPanelCriarTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
            .addGroup(jPanelCriarTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCriarTurmaLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPaneDiretoria.addTab("", jPanelCriarTurma);

        jPanelNovoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNovoUsuario.setPreferredSize(new java.awt.Dimension(640, 615));
        jPanelNovoUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genero.add(rdbFemenino);
        rdbFemenino.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        rdbFemenino.setText("Femenino");
        rdbFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFemeninoActionPerformed(evt);
            }
        });
        jPanelNovoUsuario.add(rdbFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 202, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel7.setText("DADOS DE ACESSO");
        jPanelNovoUsuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 289, -1, -1));

        area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diretoria", "Secretaria", "Professor" }));
        jPanelNovoUsuario.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 229, 395, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel8.setText("Nome de usuário:");
        jPanelNovoUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 349, -1, -1));

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel9.setText("CADASTRO DE USUÁRIO");
        jPanelNovoUsuario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 45, -1, 34));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel10.setText("Senha de acesso:");
        jPanelNovoUsuario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 377, -1, -1));

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel11.setText("Confirmar senha :");
        jPanelNovoUsuario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 405, -1, -1));

        jLabel12.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel12.setText("DADOS PESSOAIS");
        jPanelNovoUsuario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 91, -1, -1));
        jPanelNovoUsuario.add(txtConfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 400, 395, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel13.setText("Nome completo:");
        jPanelNovoUsuario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 145, -1, -1));
        jPanelNovoUsuario.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 372, 395, -1));
        jPanelNovoUsuario.add(txtNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 140, 395, -1));

        txtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuarioActionPerformed(evt);
            }
        });
        jPanelNovoUsuario.add(txtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 344, 395, -1));
        jPanelNovoUsuario.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 174, 395, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("Telefone:");
        jPanelNovoUsuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 179, -1, -1));

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel14.setText("Gênero:");
        jPanelNovoUsuario.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 204, -1, -1));

        genero.add(rdbMasculino);
        rdbMasculino.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        rdbMasculino.setText("Masculino");
        jPanelNovoUsuario.add(rdbMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 202, -1, -1));

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel15.setText("Área:");
        jPanelNovoUsuario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 229, -1, -1));

        btnCadastrarUsuario.setBackground(new java.awt.Color(255, 153, 0));
        btnCadastrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarUsuario.setText("Confirmar");
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });
        jPanelNovoUsuario.add(btnCadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 445, -1, 35));

        jButton6.setBackground(new java.awt.Color(255, 153, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Cancelar");
        jPanelNovoUsuario.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 445, -1, 35));

        jTabbedPaneDiretoria.addTab("", jPanelNovoUsuario);

        jPanelEditarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEditarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarGenero.add(rdbEditarFemenino);
        rdbEditarFemenino.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        rdbEditarFemenino.setText("Femenino");
        rdbEditarFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEditarFemeninoActionPerformed(evt);
            }
        });
        jPanelEditarUsuario.add(rdbEditarFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel16.setText("DADOS DE ACESSO");
        jPanelEditarUsuario.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 263, -1, -1));

        cbxEditarArea.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbxEditarArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diretoria", "Secretaria", "Professor" }));
        jPanelEditarUsuario.add(cbxEditarArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 209, 369, -1));

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel17.setText("Nome de usuário:");
        jPanelEditarUsuario.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 302, -1, -1));

        jLabel18.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel18.setText("EDITAR USUÁRIO");
        jPanelEditarUsuario.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 36, -1, -1));

        jLabel19.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel19.setText("Senha de acesso:");
        jPanelEditarUsuario.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 331, -1, -1));

        jLabel20.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel20.setText("Confirmar senha:");
        jPanelEditarUsuario.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 359, -1, -1));

        jLabel21.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel21.setText("DADOS PESSOAIS");
        jPanelEditarUsuario.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 77, -1, -1));
        jPanelEditarUsuario.add(editarConfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 359, 363, -1));

        jLabel22.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel22.setText("Nome completo:");
        jPanelEditarUsuario.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));
        jPanelEditarUsuario.add(editarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 331, 363, -1));
        jPanelEditarUsuario.add(txtEditarNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 117, 369, -1));
        jPanelEditarUsuario.add(txtEditarNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 297, 363, -1));
        jPanelEditarUsuario.add(txtEditarTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 152, 369, -1));

        btnEditarSalvar.setBackground(new java.awt.Color(255, 153, 0));
        btnEditarSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarSalvar.setText("Salvar");
        btnEditarSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSalvarActionPerformed(evt);
            }
        });
        jPanelEditarUsuario.add(btnEditarSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 107, 35));

        jLabel23.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel23.setText("Telefone:");
        jPanelEditarUsuario.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 157, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancelar");
        jPanelEditarUsuario.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 107, 35));

        jLabel24.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel24.setText("Gênero:");
        jPanelEditarUsuario.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 178, -1, 25));

        editarGenero.add(rdbEditarMasculino);
        rdbEditarMasculino.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        rdbEditarMasculino.setText("Masculino");
        jPanelEditarUsuario.add(rdbEditarMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 180, -1, -1));

        jLabel25.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel25.setText("Área:");
        jPanelEditarUsuario.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 212, 44, -1));

        txtId.setEditable(false);
        txtId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtId.setOpaque(true);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanelEditarUsuario.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanelEditarUsuariosLayout = new javax.swing.GroupLayout(jPanelEditarUsuarios);
        jPanelEditarUsuarios.setLayout(jPanelEditarUsuariosLayout);
        jPanelEditarUsuariosLayout.setHorizontalGroup(
            jPanelEditarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEditarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanelEditarUsuariosLayout.setVerticalGroup(
            jPanelEditarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEditarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
        );

        jTabbedPaneDiretoria.addTab("", jPanelEditarUsuarios);

        jPanelVisualizarUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVisualizarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel6.setText("VISUALIZAR USUÁRIO");
        jPanelVisualizarUsuarios.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 263, 50));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pesquisar.png"))); // NOI18N
        jPanelVisualizarUsuarios.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 320, 190));

        jTableVisualizarUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome Funcionario", "genero", "Nome Usuario", "Cargo"
            }
        ));
        jTableVisualizarUsuarios.setEnabled(false);
        jScrollPane1.setViewportView(jTableVisualizarUsuarios);

        jPanelVisualizarUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 740, 520));

        jTabbedPaneDiretoria.addTab("", jPanelVisualizarUsuarios);

        bgDiretoria.add(jTabbedPaneDiretoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -40, 740, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgDiretoria, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgDiretoria, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovousuarioActionPerformed
        // TODO add your handling code here:
        jTabbedPaneDiretoria.setSelectedIndex(2);
    }//GEN-LAST:event_btnNovousuarioActionPerformed

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
      jDialogEditarUsuario.setVisible(true);
       
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    private void btnVisualizarUuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarUuariosActionPerformed
        // TODO add your handling code here:
        jTabbedPaneDiretoria.setSelectedIndex(4);
    }//GEN-LAST:event_btnVisualizarUuariosActionPerformed

    private void btnCriarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarTurmasActionPerformed
            // TODO add your handling code here:
            jTabbedPaneDiretoria.setSelectedIndex(1);
    }//GEN-LAST:event_btnCriarTurmasActionPerformed

    private void jTabbedPaneDiretoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPaneDiretoriaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPaneDiretoriaFocusLost

    private void btnMainDiretoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainDiretoriaActionPerformed
        // TODO add your handling code here:
        jTabbedPaneDiretoria.setSelectedIndex(0);
    }//GEN-LAST:event_btnMainDiretoriaActionPerformed

    private void rdbEditarFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEditarFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbEditarFemeninoActionPerformed

    private void txtNomeTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeTurmaActionPerformed

    private void rdbFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbFemeninoActionPerformed

    private void txtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuarioActionPerformed

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        Object itemSelecionado = area.getSelectedItem();
        Secretaria secretaria = new Secretaria();
        if (itemSelecionado == "Secretaria") {
            try {
                 secretaria.setNome(txtNomeCompleto.getText());
                 secretaria.setTelefone(txtTelefone.getText());

                     if (rdbMasculino.isSelected()) {
                    secretaria.setGenero(rdbMasculino.getText());
                   } else if (rdbFemenino.isSelected()) {
                    secretaria.setGenero(rdbFemenino.getText());
                   }

                 secretaria.setNomeUsuario(txtNomeUsuario.getText());
                 secretaria.setSenha(txtSenha.getText());

                  // Inserindo na tabela funcionário
                  pst = con.prepareStatement("INSERT INTO `funcionario` (`nomeFuncionario`, `genero`, `fk_idCargo`) VALUES (?, ?, 1)", PreparedStatement.RETURN_GENERATED_KEYS);
                  pst.setString(1, secretaria.getNome());
                  pst.setString(2, secretaria.getGenero());

                  int idFuncionario;
    
                  // Executando o primeiro insert
                  int rowsAffected = pst.executeUpdate();
      
                     if (rowsAffected == 1) {
                         // Recuperando as chaves geradas
                          try (ResultSet generatedKeys = pst.getGeneratedKeys()) {
                               if (generatedKeys.next()) {
                                  idFuncionario = generatedKeys.getInt(1);

                                  // Inserindo na tabela cargo
                                  sqlUsuario = con.prepareStatement("INSERT INTO `usuario` (`nomeUsuario`, `senha`, `FK_CARGO_idCargo`,`fk_idFuncionario` ) VALUES (?, ?, 1,?)");
                                  sqlUsuario.setString(1, secretaria.getNomeUsuario());
                                  sqlUsuario.setString(2, secretaria.getSenha());
                                  sqlUsuario.setInt(3, idFuncionario);
                                  // Executando o segundo insert
                                   int usuarioRowsAffected = sqlUsuario.executeUpdate();
                                 // Inserindo na tabela telefone 
                                 sqlTelefone = con.prepareStatement("INSERT INTO `telefone` (`telefone`, `fk_idFuncionario`) VALUES (?, ?)");
                                 sqlTelefone.setString(1, secretaria.getTelefone());
                                 sqlTelefone.setInt(2, idFuncionario);
                                 int telefoneRowsAffected = sqlTelefone.executeUpdate();
                                    if (telefoneRowsAffected == 1) {
                                     JOptionPane.showMessageDialog(this, "Executado");
                                     txtNomeCompleto.setText("");
                                     txtTelefone.setText("");
                                     txtNomeUsuario.setText("");
                                     txtSenha.setText("");
                                     txtConfSenha.setText("");
                                    }
                               }
                           }
                        }
                System.out.println(secretaria.getNome());
                System.out.println(secretaria.getTelefone());
                System.out.println(secretaria.getGenero());    
            } catch (SQLException ex) {
                Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        /* Configurações do diretor*/
         Director diretor = new Director();
        if (itemSelecionado == "Diretoria") {
            try {
                diretor.setNome(txtNomeCompleto.getText());
                diretor.setTelefone(txtTelefone.getText());

                if (rdbMasculino.isSelected()) {
                    diretor.setGenero(rdbMasculino.getText());
                } else if (rdbFemenino.isSelected()) {
                    diretor.setGenero(rdbFemenino.getText());
                }

                diretor.setNomeUsuario(txtNomeUsuario.getText());
                diretor.setSenha(txtSenha.getText());

                // Inserindo em tabela funcionario 
                pst = con.prepareStatement("INSERT INTO `funcionario` (`nomeFuncionario`, `genero`, `fk_idCargo`) VALUES (?, ?, 2)", PreparedStatement.RETURN_GENERATED_KEYS);
                pst.setString(1, diretor.getNome());
                pst.setString(2, diretor.getGenero());

                int idDiretor;

                // Executando o primeiro insert
                int rowsAffected = pst.executeUpdate();

                if (rowsAffected == 1) {
                    // Recuperando as chaves geradas
                    try (ResultSet generatedKeys = pst.getGeneratedKeys()) {
                        if (generatedKeys.next()) {
                            idDiretor = generatedKeys.getInt(1);

                            // Insert into cargo table
                            sqlUsuario = con.prepareStatement("INSERT INTO `usuario` (`nomeUsuario`, `senha`, `FK_CARGO_idCargo`,`fk_idFuncionario` ) VALUES (?, ?, 2,?)");
                            sqlUsuario.setString(1, diretor.getNomeUsuario());
                            sqlUsuario.setString(2, diretor.getSenha());
                            sqlUsuario.setInt(3, idDiretor);
                            // Execute the second insert
                            int usuarioRowsAffected = sqlUsuario.executeUpdate();
                            // Insert into telefone table
                            sqlTelefone = con.prepareStatement("INSERT INTO `telefone` (`telefone`, `fk_idFuncionario`) VALUES (?, ?)");
                            sqlTelefone.setString(1, diretor.getTelefone());
                            sqlTelefone.setInt(2, idDiretor);
                            int telefoneRowsAffected = sqlTelefone.executeUpdate();
                            if (telefoneRowsAffected == 1) {
                                JOptionPane.showMessageDialog(this, "Executado");
                                txtNomeCompleto.setText("");
                                txtTelefone.setText("");
                                txtNomeUsuario.setText("");
                                txtSenha.setText("");
                                txtConfSenha.setText("");
                            }
                        }
                    }
                }

                
                System.out.println(diretor.getNome());
                System.out.println(diretor.getTelefone());
                System.out.println(diretor.getGenero());
                
            } catch (SQLException ex) {
                Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         
               
          /*Configuração do professor*/
          Professor professor = new Professor();
        if(itemSelecionado == "Professor"){
            try {
                professor.setNome(txtNomeCompleto.getText());
                professor.setTelefone(txtTelefone.getText());

                if (rdbMasculino.isSelected()) {
                    professor.setGenero(rdbMasculino.getText());
                } else if (rdbFemenino.isSelected()) {
                    professor.setGenero(rdbFemenino.getText());
                }

                professor.setNomeUsuario(txtNomeUsuario.getText());
                professor.setSenha(txtSenha.getText());

                // Insert into funcionario table
                pst = con.prepareStatement("INSERT INTO `funcionario` (`nomeFuncionario`, `genero`, `fk_idCargo`) VALUES (?, ?, 3)", PreparedStatement.RETURN_GENERATED_KEYS);
                pst.setString(1, professor.getNome());
                pst.setString(2, professor.getGenero());

                int idProfessor;

                // Execute the first insert
                int rowsAffected = pst.executeUpdate();

                if (rowsAffected == 1) {
                    // Retrieve the generated keys
                    try (ResultSet generatedKeys = pst.getGeneratedKeys()) {
                        if (generatedKeys.next()) {
                            idProfessor = generatedKeys.getInt(1);

                            // Insert into cargo table
                            sqlUsuario = con.prepareStatement("INSERT INTO `usuario` (`nomeUsuario`, `senha`, `FK_CARGO_idCargo`,`fk_idFuncionario` ) VALUES (?, ?, 3,?)");
                            sqlUsuario.setString(1, professor.getNomeUsuario());
                            sqlUsuario.setString(2, professor.getSenha());
                            sqlUsuario.setInt(3, idProfessor);
                            // Execute the second insert
                            int usuarioRowsAffected = sqlUsuario.executeUpdate();
                            // Insert into telefone table
                            sqlTelefone = con.prepareStatement("INSERT INTO `telefone` (`telefone`, `fk_idFuncionario`) VALUES (?, ?)");
                            sqlTelefone.setString(1, professor.getTelefone());
                            sqlTelefone.setInt(2, idProfessor);
                            int telefoneRowsAffected = sqlTelefone.executeUpdate();
                            if (telefoneRowsAffected == 1) {
                                JOptionPane.showMessageDialog(this, "Executado");
                                txtNomeCompleto.setText("");
                                txtTelefone.setText("");
                                txtNomeUsuario.setText("");
                                txtSenha.setText("");
                                txtConfSenha.setText("");
                            }
                        }
                    }
                }
                System.out.println(professor.getNome());
                System.out.println(professor.getTelefone());
                System.out.println(professor.getGenero());
                
            } catch (SQLException ex) {
                Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
         
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUsuarioActionPerformed
        try {
            jTabbedPaneDiretoria.setSelectedIndex(3);
            jDialogEditarUsuario.dispose();
            String idUsuario = txtUsuario.getText();
            pst = con.prepareStatement("SELECT * FROM funcionario JOIN usuario ON funcionario.idFuncionario=usuario.fk_idFuncionario join telefone on funcionario.idFuncionario=telefone.fk_idFuncionario WHERE funcionario.idFuncionario=?");
            pst.setString(1, idUsuario);
            rs = pst.executeQuery();
            if (rs.next() == true) {
                txtId.setText(rs.getString(1));
                txtEditarNomeCompleto.setText(rs.getString(2));
                txtEditarTelefone.setText(rs.getString(11));
                txtEditarNomeUsuario.setText(rs.getString(6));
                editarSenha.setText(rs.getString(7));
            } else {
                JOptionPane.showMessageDialog(this, "Dados Inexistentes");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarUsuarioActionPerformed

    private void btnEditarSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSalvarActionPerformed
        Object itemSelecionado = area.getSelectedItem();
        String id = txtId.getText();

        Secretaria secretaria = new Secretaria();
        Director diretor = new Director();
        Professor professor = new Professor();

        try {
            if ("Secretaria".equals(itemSelecionado)) {
                // Update das informacões da Secretaria 
                secretaria.setNome(txtEditarNomeCompleto.getText());
                secretaria.setTelefone(txtEditarTelefone.getText());
                secretaria.setNomeUsuario(txtEditarNomeUsuario.getText());
                secretaria.setSenha(editarSenha.getText());
                if (rdbEditarMasculino.isSelected()) {
                    secretaria.setGenero(rdbMasculino.getText());
                } else if (rdbEditarFemenino.isSelected()) {
                    secretaria.setGenero(rdbFemenino.getText());
                }
                // ... (updates semelhantes para gênero, nome de usuário e senha)

                // Update da tabela funcionario
                pst = con.prepareStatement("UPDATE `funcionario` SET `nomeFuncionario` = ?, `genero` = ? WHERE idFuncionario = ?");
                pst.setString(1, secretaria.getNome());
                pst.setString(2, secretaria.getGenero());
                pst.setString(3, id);
                int rowsAffected = pst.executeUpdate();

                if (rowsAffected == 1) {
                    // Update da tabela usuario 
                    sqlUsuario = con.prepareStatement("UPDATE `usuario` SET `nomeUsuario` = ?, `senha` =? WHERE `fk_idFuncionario`=?");
                    sqlUsuario.setString(1, secretaria.getNomeUsuario());
                    sqlUsuario.setString(2, secretaria.getSenha());
                    sqlUsuario.setString(3, id);
                    int usuarioRowsAffected = sqlUsuario.executeUpdate();

                    // Update da tabela telefone 
                    sqlTelefone = con.prepareStatement("UPDATE `telefone` SET `telefone` = ? WHERE `fk_idFuncionario` =?");
                    sqlTelefone.setString(1, secretaria.getTelefone());
                    sqlTelefone.setString(2, id);
                    int telefoneRowsAffected = sqlTelefone.executeUpdate();

                    if (usuarioRowsAffected == 1 && telefoneRowsAffected == 1) {
                        JOptionPane.showMessageDialog(this, "Executado");
                        // Limpar campos da IU
                        
                        txtEditarNomeCompleto.setText("");
                        txtEditarTelefone.setText("");
                        txtEditarNomeUsuario.setText("");
                        editarSenha.setText("");
                        rdbEditarMasculino.setSelected(false);
                        rdbEditarFemenino.setSelected(false);
                    }
                }
            } else if ("Diretoria".equals(itemSelecionado)) {
                // Update informacões da Diretoria 
                // ... (similar updates para Secretaria)
                diretor.setNome(txtEditarNomeCompleto.getText());
                diretor.setTelefone(txtEditarTelefone.getText());
                diretor.setNomeUsuario(txtEditarNomeUsuario.getText());
                diretor.setSenha(editarSenha.getText());
                if (rdbEditarMasculino.isSelected()) {
                    diretor.setGenero(rdbMasculino.getText());
                } else if (rdbEditarFemenino.isSelected()) {
                    diretor.setGenero(rdbFemenino.getText());
                }
                pst = con.prepareStatement("UPDATE `funcionario` SET `nomeFuncionario` = ?, `genero` = ? WHERE idFuncionario = ?");
                pst.setString(1, diretor.getNome());
                pst.setString(2, diretor.getGenero());
                pst.setString(3, id);
                int rowsAffected = pst.executeUpdate();

                if (rowsAffected == 1) {
                    // Update da tabela usuario
                    sqlUsuario = con.prepareStatement("UPDATE `usuario` SET `nomeUsuario` = ?, `senha` =? WHERE `fk_idFuncionario`=?");
                    sqlUsuario.setString(1, diretor.getNomeUsuario());
                    sqlUsuario.setString(2, diretor.getSenha());
                    sqlUsuario.setString(3, id);
                    int usuarioRowsAffected = sqlUsuario.executeUpdate();

                    // Update da tabela telefone 
                    sqlTelefone = con.prepareStatement("UPDATE `telefone` SET `telefone` = ? WHERE `fk_idFuncionario` =?");
                    sqlTelefone.setString(1, diretor.getTelefone());
                    sqlTelefone.setString(2, id);
                    int telefoneRowsAffected = sqlTelefone.executeUpdate();

                    if (usuarioRowsAffected == 1 && telefoneRowsAffected == 1) {
                        JOptionPane.showMessageDialog(this, "Executado");
                        // Limpar campos da IU
                        // ...
                        txtEditarNomeCompleto.setText("");
                        txtEditarTelefone.setText("");
                        txtEditarNomeUsuario.setText("");
                        editarSenha.setText("");
                        rdbEditarMasculino.setSelected(false);
                        rdbEditarFemenino.setSelected(false);
                    }
                }
            } else if ("Professor".equals(itemSelecionado)) {
                // Update informacões do Professor 
                // ... (similar updates para Secretaria)
                professor.setNome(txtEditarNomeCompleto.getText());
                professor.setTelefone(txtEditarTelefone.getText());
                professor.setNomeUsuario(txtEditarNomeUsuario.getText());
                professor.setSenha(editarSenha.getText());
                if (rdbEditarMasculino.isSelected()) {
                    professor.setGenero(rdbMasculino.getText());
                } else if (rdbEditarFemenino.isSelected()) {
                    professor.setGenero(rdbFemenino.getText());
                }
                pst = con.prepareStatement("UPDATE `funcionario` SET `nomeFuncionario` = ?, `genero` = ? WHERE idFuncionario = ?");
                pst.setString(1, professor.getNome());
                pst.setString(2, professor.getGenero());
                pst.setString(3, id);
                int rowsAffected = pst.executeUpdate();

                if (rowsAffected == 1) {
                    // Update da tabela usuario
                    sqlUsuario = con.prepareStatement("UPDATE `usuario` SET `nomeUsuario` = ?, `senha` =? WHERE `fk_idFuncionario`=?");
                    sqlUsuario.setString(1, professor.getNomeUsuario());
                    sqlUsuario.setString(2, professor.getSenha());
                    sqlUsuario.setString(3, id);
                    int usuarioRowsAffected = sqlUsuario.executeUpdate();

                    // Update da tabela  telefone
                    sqlTelefone = con.prepareStatement("UPDATE `telefone` SET `telefone` = ? WHERE `fk_idFuncionario` =?");
                    sqlTelefone.setString(1, professor.getTelefone());
                    sqlTelefone.setString(2, id);
                    int telefoneRowsAffected = sqlTelefone.executeUpdate();

                    if (usuarioRowsAffected == 1 && telefoneRowsAffected == 1) {
                        JOptionPane.showMessageDialog(this, "Executado");
                        // Limpar campos da IU
                        // ...
                        txtEditarNomeCompleto.setText("");
                        txtEditarTelefone.setText("");
                        txtEditarNomeUsuario.setText("");
                        editarSenha.setText("");
                        rdbEditarMasculino.setSelected(false);
                        rdbEditarFemenino.setSelected(false);
                    }
                }
            }

            
        } catch (SQLException ex) {
            Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            // Close resources (PreparedStatement, ResultSet, etc.)
            // ...
        }

    }//GEN-LAST:event_btnEditarSalvarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnCriarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarTurmaActionPerformed
        try {
            Turma turma = new Turma();
            turma.setNomeTurma(txtNomeTurma.getText());
            turma.setSala(txtNumSala.getText());
            turma.setIdProfessor(txtIdProfessor.getText());
            pst = con.prepareStatement("INSERT INTO `turma`( `nomeTurma`, `sala`, `fk_idProfessor`) VALUES (?,?,?)");
            pst.setString(1, turma.getNomeTurma());
            pst.setString(2, turma.getSala());
            pst.setString(3, turma.getIdProfessor());
            int rowsAffected = pst.executeUpdate();
            if (rowsAffected == 1) {
                JOptionPane.showMessageDialog(this, "Executado");
                txtNomeTurma.setText("");
                txtNumSala.setText("");
                txtIdProfessor.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCriarTurmaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       Login login = new Login();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diretoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diretoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diretoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diretoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diretoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> area;
    private javax.swing.JPanel bgDiretoria;
    private javax.swing.JPanel bgSidePanel;
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnCriarTurma;
    private javax.swing.JButton btnCriarTurmas;
    private javax.swing.JButton btnEditarSalvar;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnMainDiretoria;
    private javax.swing.JButton btnNovousuario;
    private javax.swing.JButton btnPesquisarUsuario;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVisualizarUuarios;
    private javax.swing.JComboBox<String> cbxEditarArea;
    private javax.swing.JTextField editarConfSenha;
    private javax.swing.ButtonGroup editarGenero;
    private javax.swing.JTextField editarSenha;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialogEditarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCriarTurma;
    private javax.swing.JPanel jPanelEditarUsuario;
    private javax.swing.JPanel jPanelEditarUsuarios;
    private javax.swing.JPanel jPanelNovoUsuario;
    private javax.swing.JPanel jPanelPrincipalDiretoria;
    private javax.swing.JPanel jPanelVisualizarUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneDiretoria;
    private javax.swing.JTable jTableVisualizarUsuarios;
    private javax.swing.JRadioButton rdbEditarFemenino;
    private javax.swing.JRadioButton rdbEditarMasculino;
    private javax.swing.JRadioButton rdbFemenino;
    private javax.swing.JRadioButton rdbMasculino;
    private javax.swing.JTextField txtConfSenha;
    private javax.swing.JTextField txtEditarNomeCompleto;
    private javax.swing.JTextField txtEditarNomeUsuario;
    private javax.swing.JTextField txtEditarTelefone;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdProfessor;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JTextField txtNomeTurma;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtNumSala;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    
}
