/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Diego Filipe
 */
public class Professor extends javax.swing.JFrame {

    /**
     * Criando novo formulário Professor
     */
    public Professor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgProfessor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnMainSecretaria = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        btnNovaMatricula1 = new javax.swing.JButton();
        jTabbedPaneProfessor = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanelLancarNotas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgProfessor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMainSecretaria.setBackground(new java.awt.Color(255, 153, 0));
        btnMainSecretaria.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnMainSecretaria.setForeground(new java.awt.Color(255, 255, 255));
        btnMainSecretaria.setText("Home");
        btnMainSecretaria.setBorder(null);
        btnMainSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainSecretariaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMainSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 350, 60));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo solar.png"))); // NOI18N
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        btnNovaMatricula1.setBackground(new java.awt.Color(255, 153, 0));
        btnNovaMatricula1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnNovaMatricula1.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaMatricula1.setText("Lançar Notas");
        btnNovaMatricula1.setBorder(null);
        btnNovaMatricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaMatricula1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovaMatricula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 350, 60));

        bgProfessor.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 650));

        jPanelHome.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Profesor.png"))); // NOI18N
        jPanelHome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel37.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel37.setText("Bem-vindo Professor(a)");
        jPanelHome.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("Seu espaço para lançar notas e acessar ferramentas");
        jPanelHome.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setText("essenciais para um ensino dinâmico e eficaz.");
        jPanelHome.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jTabbedPaneProfessor.addTab("tab1", jPanelHome);

        jPanelLancarNotas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLancarNotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("LANÇAR NOTAS");
        jPanelLancarNotas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 164, 86));

        jTabbedPaneProfessor.addTab("tab6", jPanelLancarNotas);

        bgProfessor.add(jTabbedPaneProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -40, 810, 680));

        btnSair.setText("sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnSair)
                .addGap(0, 1088, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 627, Short.MAX_VALUE)
                .addComponent(btnSair))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainSecretariaActionPerformed
        // TODO add your handling code here:
        jTabbedPaneProfessor.setSelectedIndex(0);
    }//GEN-LAST:event_btnMainSecretariaActionPerformed

    private void btnNovaMatricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaMatricula1ActionPerformed
        jTabbedPaneProfessor.setSelectedIndex(1);
    }//GEN-LAST:event_btnNovaMatricula1ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
           Login login = new Login();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgProfessor;
    private javax.swing.JButton btnMainSecretaria;
    private javax.swing.JButton btnNovaMatricula1;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelLancarNotas;
    private javax.swing.JTabbedPane jTabbedPaneProfessor;
    // End of variables declaration//GEN-END:variables
}
