/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import Classes.Aluno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Random;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Samuel
 */
public class Secretaria extends javax.swing.JFrame {

    /**
     * Cria novo formulário Secretaria
     */
    public Secretaria() {
        initComponents();
        Connect();
       
        fetch();
    }
    Connection con;
    PreparedStatement pst;
    PreparedStatement sql;
    PreparedStatement sqlUsuario, sqlTelefone;
    ResultSet rs;

    private void fetch() {
        int i;
        try {
            pst = con.prepareStatement("SELECT* FROM aluno JOIN turma ON aluno.fk_idTurma=turma.idTurma JOIN classe ON aluno.fk_idClasse= classe.idClasse JOIN funcionario on turma.fk_idProfessor=funcionario.idFuncionario");
            rs = pst.executeQuery();
            ResultSetMetaData rsm = rs.getMetaData();
            i = rsm.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) jTableMatriculas.getModel();
            df.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int j = 1; j <= i; j++) {
                    v2.add(rs.getString("nome_aluno"));
                    v2.add(rs.getString("genero"));
                    v2.add(rs.getString("num_bilhete"));
                    v2.add(rs.getString("numMatricula"));
                    v2.add(rs.getString("nomeClasse"));
                    v2.add(rs.getString("nomeTurma"));
                    v2.add(rs.getString("nomeFuncionario"));

                }
                df.addRow(v2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/solar", "root", "1234@");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogEditarMatricula = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jDialogVisualizarMatricula = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        genero = new javax.swing.ButtonGroup();
        bgSecretaria = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnImprimirPautas = new javax.swing.JButton();
        btnImprimirBoletim = new javax.swing.JButton();
        btnMainSecretaria = new javax.swing.JButton();
        btnEditarMatricula = new javax.swing.JButton();
        btnVisualizarMatriculas = new javax.swing.JButton();
        btnNovaMatricula = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jTabbedPaneSecretaria = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanelNovaMatricula = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        lblInformacaoMatricula = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNumeroBI = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rbdGeneroMasculino = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        rbdGeneroFemenino = new javax.swing.JRadioButton();
        txtNomeEncarregado = new javax.swing.JTextField();
        lblInformacaoPessoais = new javax.swing.JLabel();
        txtRelacaoAluno = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTelefoneEncarregado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lblInformacaoEncarregado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtIdClasse = new javax.swing.JTextField();
        txtIdTurma = new javax.swing.JTextField();
        jPanelEditarMatricula = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jPanelMatriculasFeitas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatriculas = new javax.swing.JTable();
        jPanelBoletim = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelPautas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jDialogEditarMatricula.setTitle("Editar Matricula");
        jDialogEditarMatricula.setMinimumSize(new java.awt.Dimension(390, 320));
        jDialogEditarMatricula.setModal(true);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Digite o numero de processo");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 201, -1));

        jButton3.setText("Pesquisar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_45_1.png"))); // NOI18N
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 70, 70));

        javax.swing.GroupLayout jDialogEditarMatriculaLayout = new javax.swing.GroupLayout(jDialogEditarMatricula.getContentPane());
        jDialogEditarMatricula.getContentPane().setLayout(jDialogEditarMatriculaLayout);
        jDialogEditarMatriculaLayout.setHorizontalGroup(
            jDialogEditarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        jDialogEditarMatriculaLayout.setVerticalGroup(
            jDialogEditarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditarMatriculaLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogVisualizarMatricula.setTitle("Visualizar turmas");
        jDialogVisualizarMatricula.setMinimumSize(new java.awt.Dimension(378, 331));
        jDialogVisualizarMatricula.setModal(true);
        jDialogVisualizarMatricula.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_45_1.png"))); // NOI18N
        jDialogVisualizarMatricula.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 38, -1, 78));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turma A", "Turma B", " " }));
        jDialogVisualizarMatricula.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 150, 156, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pré", "1ª Classe", "2ª Classe", "3ª Classe", "4ª Classe", "5ª Classe", "6ª Classe" }));
        jDialogVisualizarMatricula.getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 207, 156, -1));

        jLabel21.setText("Selecione a turma");
        jDialogVisualizarMatricula.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 128, 138, -1));

        jLabel22.setText("Selecione a classe");
        jDialogVisualizarMatricula.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 179, 111, -1));

        jButton4.setText("Visualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDialogVisualizarMatricula.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 241, 99, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secretaria");
        setName("Secretaria"); // NOI18N

        bgSecretaria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnImprimirPautas.setBackground(new java.awt.Color(255, 153, 0));
        btnImprimirPautas.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnImprimirPautas.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirPautas.setText("Pautas");
        btnImprimirPautas.setBorder(null);
        btnImprimirPautas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirPautasActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimirPautas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 350, 60));

        btnImprimirBoletim.setBackground(new java.awt.Color(255, 153, 0));
        btnImprimirBoletim.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnImprimirBoletim.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirBoletim.setText("Boletim");
        btnImprimirBoletim.setBorder(null);
        btnImprimirBoletim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirBoletimActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimirBoletim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 350, 60));

        btnMainSecretaria.setBackground(new java.awt.Color(255, 153, 0));
        btnMainSecretaria.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnMainSecretaria.setForeground(new java.awt.Color(255, 255, 255));
        btnMainSecretaria.setText("Home");
        btnMainSecretaria.setBorder(null);
        btnMainSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainSecretariaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMainSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 350, 60));

        btnEditarMatricula.setBackground(new java.awt.Color(255, 153, 0));
        btnEditarMatricula.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnEditarMatricula.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarMatricula.setText("Editar Matrícula");
        btnEditarMatricula.setBorder(null);
        btnEditarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 350, 60));

        btnVisualizarMatriculas.setBackground(new java.awt.Color(255, 153, 0));
        btnVisualizarMatriculas.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnVisualizarMatriculas.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarMatriculas.setText("Matrículas Feitas");
        btnVisualizarMatriculas.setBorder(null);
        btnVisualizarMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarMatriculasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVisualizarMatriculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 350, 60));

        btnNovaMatricula.setBackground(new java.awt.Color(255, 153, 0));
        btnNovaMatricula.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnNovaMatricula.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaMatricula.setText("Matrícula");
        btnNovaMatricula.setBorder(null);
        btnNovaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovaMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 350, 60));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo solar.png"))); // NOI18N
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));

        bgSecretaria.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 650));

        jPanelHome.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Secretaria.png"))); // NOI18N
        jPanelHome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel37.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel37.setText("Bem-vindo à Secretaria");
        jPanelHome.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("a administração escolar.");
        jPanelHome.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("Aqui você pode gerenciar matrículas, editar informações de alunos,");
        jPanelHome.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setText("acessar boletins e consultar pautas, otimizando ");
        jPanelHome.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jTabbedPaneSecretaria.addTab("tab1", jPanelHome);

        jPanelNovaMatricula.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNovaMatricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel11.setText("Telefone:");
        jPanelNovaMatricula.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, 20));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel8.setText("NOVA MATRÍCULA");
        jPanelNovaMatricula.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        txtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoActionPerformed(evt);
            }
        });
        jPanelNovaMatricula.add(txtNomeAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 410, -1));

        lblInformacaoMatricula.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblInformacaoMatricula.setText("Informações de Matrícula");
        jPanelNovaMatricula.add(lblInformacaoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel10.setText("Nome do aluno:");
        jPanelNovaMatricula.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 20));

        txtNumeroBI.setText(" ");
        jPanelNovaMatricula.add(txtNumeroBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 410, -1));

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel13.setText("Gênero:");
        jPanelNovaMatricula.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 60, 20));

        genero.add(rbdGeneroMasculino);
        rbdGeneroMasculino.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        rbdGeneroMasculino.setText("Masculino");
        jPanelNovaMatricula.add(rbdGeneroMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, 20));

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel14.setText("Número de BI:");
        jPanelNovaMatricula.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 110, 20));

        genero.add(rbdGeneroFemenino);
        rbdGeneroFemenino.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        rbdGeneroFemenino.setText("Femenino");
        jPanelNovaMatricula.add(rbdGeneroFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, 20));
        jPanelNovaMatricula.add(txtNomeEncarregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 410, -1));

        lblInformacaoPessoais.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblInformacaoPessoais.setText("Informações Pessoais ");
        jPanelNovaMatricula.add(lblInformacaoPessoais, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanelNovaMatricula.add(txtRelacaoAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 410, -1));

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel17.setText("Nome completo:");
        jPanelNovaMatricula.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));
        jPanelNovaMatricula.add(txtTelefoneEncarregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 410, -1));

        jLabel18.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel18.setText("Relação com o aluno:");
        jPanelNovaMatricula.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        lblInformacaoEncarregado.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblInformacaoEncarregado.setText("Informações do Encarregado");
        jPanelNovaMatricula.add(lblInformacaoEncarregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("Número de Matrícula:");
        jPanelNovaMatricula.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, 30));

        txtNumeroMatricula.setEditable(false);
        jPanelNovaMatricula.add(txtNumeroMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 130, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("ID Classe:");
        jPanelNovaMatricula.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 100, 30));

        jLabel47.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel47.setText("ID Turma:");
        jPanelNovaMatricula.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 80, 30));

        btnConfirmar.setBackground(new java.awt.Color(255, 153, 0));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanelNovaMatricula.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, -1, 30));

        btnCancelar.setBackground(new java.awt.Color(255, 153, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        jPanelNovaMatricula.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 90, 30));

        txtIdClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClasseActionPerformed(evt);
            }
        });
        jPanelNovaMatricula.add(txtIdClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 140, -1));
        jPanelNovaMatricula.add(txtIdTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 140, -1));

        jTabbedPaneSecretaria.addTab("tab2", jPanelNovaMatricula);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel23.setText("Telefone de contacto:");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, 20));

        jLabel24.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel24.setText("EDITAR MATRÍCULA");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 470, -1));

        jLabel25.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel25.setText("Informações do Encarregado");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        jPanel9.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 470, -1));

        jLabel26.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel26.setText("Nome do aluno:");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 20));

        jTextField11.setText(" ");
        jPanel9.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 470, -1));

        jLabel27.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel27.setText("Data de nascimento:");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));
        jPanel9.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 470, -1));

        jLabel28.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel28.setText("Género:");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 180, 60, -1));

        jRadioButton3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jRadioButton3.setText("Masculino");
        jPanel9.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel29.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel29.setText("Número de BI:");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jRadioButton4.setText("Femenino");
        jPanel9.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel30.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel30.setText("Endereço:");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 110, -1));
        jPanel9.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 470, -1));

        jLabel31.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel31.setText("Informações Pessoais ");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel9.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 470, -1));

        jLabel32.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel32.setText("Nome completo:");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));
        jPanel9.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 470, -1));

        jLabel33.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel33.setText("Relação com o aluno:");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 160, 20));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salvar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, -1, 30));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, -1, 30));

        jLabel41.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel41.setText("Informações de Matrícula");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel42.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel42.setText("Classe:");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 60, 30));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 470, -1));

        jLabel48.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel48.setText("Turma:");
        jPanel9.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, 30));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 470, -1));

        jLabel43.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel43.setText("Número de Matrícula:");
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, 30));
        jPanel9.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 470, -1));

        javax.swing.GroupLayout jPanelEditarMatriculaLayout = new javax.swing.GroupLayout(jPanelEditarMatricula);
        jPanelEditarMatricula.setLayout(jPanelEditarMatriculaLayout);
        jPanelEditarMatriculaLayout.setHorizontalGroup(
            jPanelEditarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        jPanelEditarMatriculaLayout.setVerticalGroup(
            jPanelEditarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );

        jTabbedPaneSecretaria.addTab("tab3", jPanelEditarMatricula);

        jPanelMatriculasFeitas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMatriculasFeitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Matriculas Feitas");
        jPanelMatriculasFeitas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 27, 164, 86));

        jTableMatriculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome Completo", "Genero", "Numero Bilhete", "Numero de Matricula", "Classe", "Turma", "Professor(a)"
            }
        ));
        jTableMatriculas.setEnabled(false);
        jScrollPane1.setViewportView(jTableMatriculas);

        jPanelMatriculasFeitas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 810, 540));

        jTabbedPaneSecretaria.addTab("tab4", jPanelMatriculasFeitas);

        jPanelBoletim.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Boletim");

        javax.swing.GroupLayout jPanelBoletimLayout = new javax.swing.GroupLayout(jPanelBoletim);
        jPanelBoletim.setLayout(jPanelBoletimLayout);
        jPanelBoletimLayout.setHorizontalGroup(
            jPanelBoletimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBoletimLayout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(334, 334, 334))
        );
        jPanelBoletimLayout.setVerticalGroup(
            jPanelBoletimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoletimLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addContainerGap(575, Short.MAX_VALUE))
        );

        jTabbedPaneSecretaria.addTab("tab5", jPanelBoletim);

        jPanelPautas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Pautas");

        javax.swing.GroupLayout jPanelPautasLayout = new javax.swing.GroupLayout(jPanelPautas);
        jPanelPautas.setLayout(jPanelPautasLayout);
        jPanelPautasLayout.setHorizontalGroup(
            jPanelPautasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPautasLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(606, Short.MAX_VALUE))
        );
        jPanelPautasLayout.setVerticalGroup(
            jPanelPautasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPautasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(534, Short.MAX_VALUE))
        );

        jTabbedPaneSecretaria.addTab("tab6", jPanelPautas);

        bgSecretaria.add(jTabbedPaneSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -40, 810, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgSecretaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgSecretaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirPautasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirPautasActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnImprimirPautasActionPerformed

    private void btnImprimirBoletimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirBoletimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirBoletimActionPerformed

    private void btnMainSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainSecretariaActionPerformed
        // TODO add your handling code here:
        jTabbedPaneSecretaria.setSelectedIndex(0);
    }//GEN-LAST:event_btnMainSecretariaActionPerformed

    private void btnEditarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMatriculaActionPerformed
        jDialogEditarMatricula.setVisible(true);
    }//GEN-LAST:event_btnEditarMatriculaActionPerformed

    private void btnVisualizarMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarMatriculasActionPerformed
         jTabbedPaneSecretaria.setSelectedIndex(3);
    }//GEN-LAST:event_btnVisualizarMatriculasActionPerformed

    private void btnNovaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaMatriculaActionPerformed
        // TODO add your handling code here:
        jTabbedPaneSecretaria.setSelectedIndex(1);
    }//GEN-LAST:event_btnNovaMatriculaActionPerformed

    private void txtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPaneSecretaria.setSelectedIndex(2);
        jDialogEditarMatricula.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
       jDialogVisualizarMatricula.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        Random ra = new Random();
        int numeroMatricula = ra.nextInt(999999 - 10000 + 1) + 10000;
        txtNumeroMatricula.setText(Integer.toString(numeroMatricula));
        Aluno aluno = new Aluno();
        try {
            aluno.setNome(txtNomeAluno.getText());
            aluno.setTelefone(txtTelefoneEncarregado.getText());

            if (rbdGeneroMasculino.isSelected()) {
                aluno.setGenero(rbdGeneroMasculino.getText());
            } else if (rbdGeneroFemenino.isSelected()) {
                aluno.setGenero(rbdGeneroFemenino.getText());
            }
            aluno.setNumeroBI(txtNumeroBI.getText());
            aluno.setClasse(txtIdClasse.getText());
            aluno.setTurma(txtIdTurma.getText());

            // Insert da tabela  aluno
            pst = con.prepareStatement("INSERT INTO `aluno`(`nome_aluno`, `num_bilhete`, `genero`, `numMatricula`, `fk_idTurma`, `fk_idClasse`) VALUES (?,?,?,?,?,?)", PreparedStatement.RETURN_GENERATED_KEYS);
            pst.setString(1, aluno.getNome());
            pst.setString(2, aluno.getNumeroBI());
            pst.setString(3, aluno.getGenero());
            pst.setString(4, Integer.toString(numeroMatricula));
            pst.setString(5, aluno.getTurma());
            pst.setString(6, aluno.getClasse());
           pst.executeUpdate();
            
            pst = con.prepareStatement("INSERT INTO `classe_turma` ( `fk_idTurma`, `fk_idClasse`) VALUES ( ?, ?)");
            pst.setString(1, aluno.getTurma());
            pst.setString(2, aluno.getClasse());
            int classe_turmaRowsAffected = pst.executeUpdate();
            if (classe_turmaRowsAffected  == 1) {
                JOptionPane.showMessageDialog(this, "Executado");

            }

        } catch (SQLException ex) {
            Logger.getLogger(Diretoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtIdClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClasseActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
           Login login = new Login();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgSecretaria;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditarMatricula;
    private javax.swing.JButton btnImprimirBoletim;
    private javax.swing.JButton btnImprimirPautas;
    private javax.swing.JButton btnMainSecretaria;
    private javax.swing.JButton btnNovaMatricula;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVisualizarMatriculas;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JDialog jDialogEditarMatricula;
    private javax.swing.JDialog jDialogVisualizarMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBoletim;
    private javax.swing.JPanel jPanelEditarMatricula;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelMatriculasFeitas;
    private javax.swing.JPanel jPanelNovaMatricula;
    private javax.swing.JPanel jPanelPautas;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneSecretaria;
    private javax.swing.JTable jTableMatriculas;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblInformacaoEncarregado;
    private javax.swing.JLabel lblInformacaoMatricula;
    private javax.swing.JLabel lblInformacaoPessoais;
    private javax.swing.JRadioButton rbdGeneroFemenino;
    private javax.swing.JRadioButton rbdGeneroMasculino;
    private javax.swing.JTextField txtIdClasse;
    private javax.swing.JTextField txtIdTurma;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtNomeEncarregado;
    private javax.swing.JTextField txtNumeroBI;
    private javax.swing.JTextField txtNumeroMatricula;
    private javax.swing.JTextField txtRelacaoAluno;
    private javax.swing.JTextField txtTelefoneEncarregado;
    // End of variables declaration//GEN-END:variables
}
